version: "2.1"
services:
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - AUTO_UPDATE=true #optional
    volumes:
      - /media/newhd/docker/jackett/config:/config
      - /media/newhd:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
   
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /media/newhd/docker/radarr/config:/config
      - /media/newhd/Movies/English:/movies
      - /media/newhd:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
 
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - /media/newhd/docker/sonarr/config:/config
      - /media/newhd/Shows:/tv
      - /media/newhd:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped