version: "2.1"
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /media/newhd/docker/portainer/data:/data
    ports:
      - 8000:8000
      - 9443:9443
      - 9000:9000
    restart: unless-stopped
  # agent:
  #   image: portainer/portainer-ce:latest
  #   container_name: portainer-agent
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /var/lib/docker/volumes:/var/lib/docker/volumes
  #   ports:
  #     - 9001:9001
  #     - 9000:9000
  #   restart: unless-stopped
