version: "2.1"
services:
  transmission:
    image: lscr.io/linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=India/Kolkata
    volumes:
      - /media/newhd/docker/transmission/config:/config
      - /media/newhd:/downloads
      - /media/newhd/docker/transmission/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
